package basic.swing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;

/**
 *
 * @author Administrator
 */
public class JDialogDemo extends javax.swing.JDialog {

    /** Creates new form JDialogDemo
     * @param parent
     * @param modal
     */
    public JDialogDemo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPopupMenu1 = new JPopupMenu();
        jMenuItem2 = new JMenuItem();
        jRadioButtonMenuItem1 = new JRadioButtonMenuItem();
        jLabel1 = new JLabel();
        jButtonMessage = new JButton();
        jButtonConfirm = new JButton();
        jButtonInput = new JButton();
        jButton1 = new JButton();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        jMenuItem1 = new JMenuItem();
        jCheckBoxMenuItem1 = new JCheckBoxMenuItem();
        jMenu2 = new JMenu();
        jMenu3 = new JMenu();

        jMenuItem2.setText("jMenuItem2");
        jPopupMenu1.add(jMenuItem2);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
        jPopupMenu1.add(jRadioButtonMenuItem1);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JDialog example");
        setAlwaysOnTop(true);
        setModal(true);

        jLabel1.setText("jLabel1");

        jButtonMessage.setText("message dialog");
        jButtonMessage.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonMessageActionPerformed(evt);
            }
        });

        jButtonConfirm.setText("confirm dialog");
        jButtonConfirm.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonInput.setText("input dialog");
        jButtonInput.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonInputActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK));
        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jCheckBoxMenuItem1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInput)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1))
                    .addComponent(jButtonConfirm)
                    .addComponent(jButtonMessage)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMessage)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirm)
                        .addPreferredGap(ComponentPlacement.RELATED)
                        .addComponent(jButtonInput))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton1)))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void jButtonMessageActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonMessageActionPerformed
        //参数依次为： ParentComponent,String message,String title, int MessageType
        //返回void
        JOptionPane.showMessageDialog(this, "message dialog", "显示一个对话框", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonMessageActionPerformed

    private void jButtonConfirmActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        //parent component,string message,string title,int option_type, int messageType
        //返回int
        int i = JOptionPane.showConfirmDialog(this, "confirm dialog", "显示一个确认对话框", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        switch (i) {
            case JOptionPane.YES_OPTION:
                this.jLabel1.setText("yes" + i);
                break;
            case JOptionPane.NO_OPTION:
                this.jLabel1.setText("no" + i);
                break;
            case JOptionPane.CANCEL_OPTION:
                this.jLabel1.setText("cancel" + 1);
                break;
            case JOptionPane.CLOSED_OPTION:
                this.jLabel1.setText("closed" + 1);
                break;
        }
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonInputActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonInputActionPerformed
        //parent component,message,title,messageType
        //返回string
        String str = JOptionPane.showInputDialog(this, "一个input dialog", "input dialog", JOptionPane.INFORMATION_MESSAGE);
        this.jLabel1.setText(str);
    }//GEN-LAST:event_jButtonInputActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         jPopupMenu1.show(this, 34, 34);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                JDialogDemo dialog = new JDialogDemo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton jButton1;
    JButton jButtonConfirm;
    JButton jButtonInput;
    JButton jButtonMessage;
    JCheckBoxMenuItem jCheckBoxMenuItem1;
    JLabel jLabel1;
    JMenu jMenu1;
    JMenu jMenu2;
    JMenu jMenu3;
    JMenuBar jMenuBar1;
    JMenuItem jMenuItem1;
    JMenuItem jMenuItem2;
    JPopupMenu jPopupMenu1;
    JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
