/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SuperSwingComponentTest2.java
 *
 * Created on 2011-10-25, 21:49:01
 */
package basic.swing;

import java.util.logging.Level;
import java.util.logging.Logger;
import weka.gui.arffviewer.ArffViewer;

/**
 *
 * @author libiun
 */
public class SuperSwingComponentTest2 extends javax.swing.JFrame {

    /** Creates new form SuperSwingComponentTest2 */
    public SuperSwingComponentTest2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        buttonGroupOne = new javax.swing.ButtonGroup();
        jSplitPaneGlobal = new javax.swing.JSplitPane();
        jSplitPaneRight = new javax.swing.JSplitPane();
        jPanelRightTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelRightBottom = new javax.swing.JPanel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jRadioButtonHate = new javax.swing.JRadioButton();
        jRadioButtonCommon = new javax.swing.JRadioButton();
        jRadioButtonLike = new javax.swing.JRadioButton();
        jCheckBoxBaggio = new javax.swing.JCheckBox();
        jCheckBoxBeckham = new javax.swing.JCheckBox();
        jCheckBoxFigo = new javax.swing.JCheckBox();
        jButtonEnter = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelLeft = new javax.swing.JPanel();
        jLabelList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSport = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPaneGlobal.setDividerLocation(100);
        jSplitPaneGlobal.setDividerSize(3);

        jSplitPaneRight.setDividerLocation(80);
        jSplitPaneRight.setDividerSize(3);
        jSplitPaneRight.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel1.setText("这里将显示动作");

        javax.swing.GroupLayout jPanelRightTopLayout = new javax.swing.GroupLayout(jPanelRightTop);
        jPanelRightTop.setLayout(jPanelRightTopLayout);
        jPanelRightTopLayout.setHorizontalGroup(
            jPanelRightTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
        jPanelRightTopLayout.setVerticalGroup(
            jPanelRightTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        jSplitPaneRight.setTopComponent(jPanelRightTop);

        jLabelAddress.setText("地址：");

        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        buttonGroupOne.add(jRadioButtonHate);
        jRadioButtonHate.setText("讨厌");
        jRadioButtonHate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonHateItemStateChanged(evt);
            }
        });

        buttonGroupOne.add(jRadioButtonCommon);
        jRadioButtonCommon.setSelected(true);
        jRadioButtonCommon.setText("一般");
        jRadioButtonCommon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonCommonItemStateChanged(evt);
            }
        });

        buttonGroupOne.add(jRadioButtonLike);
        jRadioButtonLike.setText("喜欢");
        jRadioButtonLike.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonLikeItemStateChanged(evt);
            }
        });

        jCheckBoxBaggio.setText("巴乔");
        jCheckBoxBaggio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxBaggioItemStateChanged(evt);
            }
        });

        jCheckBoxBeckham.setText("贝克汉姆");
        jCheckBoxBeckham.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxBeckhamItemStateChanged(evt);
            }
        });

        jCheckBoxFigo.setText("菲戈");
        jCheckBoxFigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxFigoItemStateChanged(evt);
            }
        });

        jButtonEnter.setText("确定");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonCancel.setText("取消");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButton1.setText("lanuch ArffViewer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRightBottomLayout = new javax.swing.GroupLayout(jPanelRightBottom);
        jPanelRightBottom.setLayout(jPanelRightBottomLayout);
        jPanelRightBottomLayout.setHorizontalGroup(
            jPanelRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRightBottomLayout.createSequentialGroup()
                        .addComponent(jRadioButtonHate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonCommon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonLike))
                    .addGroup(jPanelRightBottomLayout.createSequentialGroup()
                        .addComponent(jCheckBoxBaggio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxBeckham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxFigo))
                    .addComponent(jButton1)
                    .addGroup(jPanelRightBottomLayout.createSequentialGroup()
                        .addComponent(jButtonEnter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addGroup(jPanelRightBottomLayout.createSequentialGroup()
                        .addComponent(jLabelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanelRightBottomLayout.setVerticalGroup(
            jPanelRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightBottomLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddress)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonHate)
                    .addComponent(jRadioButtonCommon)
                    .addComponent(jRadioButtonLike))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxBaggio)
                    .addComponent(jCheckBoxBeckham)
                    .addComponent(jCheckBoxFigo))
                .addGap(18, 18, 18)
                .addGroup(jPanelRightBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnter)
                    .addComponent(jButtonCancel))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jSplitPaneRight.setRightComponent(jPanelRightBottom);

        jSplitPaneGlobal.setRightComponent(jSplitPaneRight);

        jLabelList.setText("列表项");

        jListSport.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "西甲", "英超", "意甲", "法甲", "中超", "俄操", "广西", "日本", "韩国" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListSport.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSportValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListSport);

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
        );

        jSplitPaneGlobal.setLeftComponent(jPanelLeft);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        String s = this.jTextFieldAddress.getText();
        if (s != null && !s.equals("")) {
            this.jLabel1.setText("你输入了：" + s);
        } else {
            this.jLabel1.setText("你没有输入内容。");
        }
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jListSportValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSportValueChanged
        String s = (String) this.jListSport.getSelectedValue();
        jLabel1.setText("your choice is:" + s);
    }//GEN-LAST:event_jListSportValueChanged

    private void jRadioButtonHateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonHateItemStateChanged
        this.jLabel1.setText("hate");
    }//GEN-LAST:event_jRadioButtonHateItemStateChanged

    private void jRadioButtonCommonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonCommonItemStateChanged
        this.jLabel1.setText("common");
    }//GEN-LAST:event_jRadioButtonCommonItemStateChanged

    private void jRadioButtonLikeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonLikeItemStateChanged
        this.jLabel1.setText("like");
    }//GEN-LAST:event_jRadioButtonLikeItemStateChanged

    private void jCheckBoxBaggioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxBaggioItemStateChanged
        if (this.jCheckBoxBeckham.isSelected()) {
            this.jLabel1.setText("you like baggio");
        } else {
            this.jLabel1.setText("you dislike baggio");
        }
    }//GEN-LAST:event_jCheckBoxBaggioItemStateChanged

    private void jCheckBoxBeckhamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxBeckhamItemStateChanged
        if (this.jCheckBoxBeckham.isSelected()) {
            this.jLabel1.setText("you like beckham");
        } else {
            this.jLabel1.setText("you dislike beckham");
        }
    }//GEN-LAST:event_jCheckBoxBeckhamItemStateChanged

    private void jCheckBoxFigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxFigoItemStateChanged
        if (this.jCheckBoxBeckham.isSelected()) {
            this.jLabel1.setText("you like figo");
        } else {
            this.jLabel1.setText("you dislike figo");
        }
    }//GEN-LAST:event_jCheckBoxFigoItemStateChanged

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        this.jLabel1.setText("you put ok");    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.jLabel1.setText("you put cancel");
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ArffViewer arffViewer = new weka.gui.arffviewer.ArffViewer();
        String[] args={"f:/write/weka-3-6/data/cpu.arff"};
        try {
            ArffViewer.main(args);
        } catch (Exception ex) {
            Logger.getLogger(SuperSwingComponentTest2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperSwingComponentTest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperSwingComponentTest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperSwingComponentTest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperSwingComponentTest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SuperSwingComponentTest2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOne;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JCheckBox jCheckBoxBaggio;
    private javax.swing.JCheckBox jCheckBoxBeckham;
    private javax.swing.JCheckBox jCheckBoxFigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelList;
    private javax.swing.JList jListSport;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRightBottom;
    private javax.swing.JPanel jPanelRightTop;
    private javax.swing.JRadioButton jRadioButtonCommon;
    private javax.swing.JRadioButton jRadioButtonHate;
    private javax.swing.JRadioButton jRadioButtonLike;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPaneGlobal;
    private javax.swing.JSplitPane jSplitPaneRight;
    private javax.swing.JTextField jTextFieldAddress;
    // End of variables declaration//GEN-END:variables
}
